### ISSUE TITLE
Пустые папки

### ISSUE THREAD

**Issue by amvasiljev** [dsbasko/create-react-component#3]
Привет, это прекрасный компонент. Использую его для компонентов pug-scss, а также для создания именованной структуры папок картинок.  Раньше пользовался new fractal folder.
Но. Компонент **не создает пустые папки**, и чтобы мне создать вложенность name/webp, мне приходится ставить внутрь webp какой-то файл (я делаю test.md). Сильно на скорость не влияет, но было бы хорошо, если бы можно было просто создавать структуру папок по шаблону.
Спасибо.

P.S. и для глобальной видимости мне пришлось прописать вот такой путь /.vscode/cch-template

**Comment by dsbasko** [comment]
Салют!
Спасибо за тёплые слова, приятно знать что расширение приносит пользу.

Добавил поддержку создания пустых директорий в версии 2.3.0. Можете просто обновить расширение. 4abc238

**Comment by amvasiljev** [comment]
Благодарю.
